### ISSUE TITLE
Help Required on semantic segmentation example of Potsdam

### ISSUE THREAD

**Issue by gunjanthakuria** [azavea/raster-vision-examples#51]
Hi, 

  I just started out with deep learning and found this to be an excellent source. Thanks a lot . However being an absolute beginner I do have certain doubts. I started with the Potsdam example of Semantic Segmentation. I tried out the set up locally and it is executing; however I do not see any outputs in the folder that I have defined. I have defined the following data folder:
1. Data_URI = This points to my S3 bucket with the source data files satellite images
2. Root_URI= This points to a folder in my local machine for output storing

rastervision run local -e potsdam.semantic_segmentation \
    -a test_run True -a root_uri ${ROOT_URI} -a data_uri ${DATA_URI}

I am trying to figure out if the set up ran as expected and if so why am I not able to see the output in the folder.Attached is the Terminal window. Many thanks for your help!

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
TensorBoard 1.10.0 at http://932c17caf67d:6006 (Press CTRL+C to quit)
INFO:tensorflow:Training on train set
INFO:tensorflow:Initializing model from path: /tmp/tmpzyxwc5qv/tmp61jrqise/http/download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug/model.ckpt-30000
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/learning.py:737: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2019-03-29 08:57:45.278047: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from /tmp/tmpzyxwc5qv/tmp61jrqise/http/download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug/model.ckpt-30000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path Users/gunjanthakuria/Desktop/projects/data_project/Satellite/postdam_contest/raster-vision-examples-master/output/train/potsdam-seg/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
2019-03-29 08:57:58.398151: W tensorflow/core/framework/allocator.cc:108] Allocation of 12582912 exceeds 10% of system memory.
2019-03-29 08:57:59.072704: W tensorflow/core/framework/allocator.cc:108] Allocation of 67108864 exceeds 10% of system memory.
2019-03-29 08:57:59.297481: W tensorflow/core/framework/allocator.cc:108] Allocation of 67108864 exceeds 10% of system memory.
2019-03-29 08:57:59.380239: W tensorflow/core/framework/allocator.cc:108] Allocation of 79691776 exceeds 10% of system memory.
2019-03-29 08:57:59.518586: W tensorflow/core/framework/allocator.cc:108] Allocation of 79691776 exceeds 10% of system memory.
INFO:tensorflow:Recording summary at step 0.
INFO:tensorflow:Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
2019-03-29 08:58:16:rastervision.backend.tf_deeplab: INFO - Exporting frozen graph (Users/gunjanthakuria/Desktop/projects/data_project/Satellite/postdam_contest/raster-vision-examples-master/output/train/potsdam-seg/model)
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:Prepare to export model to: Users/gunjanthakuria/Desktop/projects/data_project/Satellite/postdam_contest/raster-vision-examples-master/output/train/potsdam-seg/model
INFO:tensorflow:Exported model performs single-scale inference.
2019-03-29 08:58:33.755165: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

[Terminal Saved Output.pdf](https://github.com/azavea/raster-vision-examples/files/3022539/Terminal.Saved.Output.pdf)

**Comment by lewfish** [comment]
From the log you provided it looks like the output is going to `Users/gunjanthakuria/Desktop/projects/data_project/Satellite/postdam_contest/raster-vision-examples-master/output/`

**Comment by lewfish** [comment]
That appears to be a relative path (because it doesn't start with a forward slash) so that directory should be located in the directory you ran Raster Vision from.

**Comment by gunjanthakuria** [comment]
Thanks, I also tried running the program using AWS batch having set up the requirement AMIs. 

     My input and output folder are in S3:
DATA_URI=https://s3.ap-south-1.amazonaws.com/gunjanpotsdam/data
ROOT_URI= http://s3.amazonaws.com/postdamout
I ran the batch command : rastervision run aws_batch -e potsdam.semantic_segmentation     -a root_uri ${ROOT_URI} -a data_uri ${DATA_URI}

However I don't see any outputs in the S3 bucket "http://s3.amazonaws.com/postdamout" nor is there any error . Am I making any mistake here ? Please find below the logs:

root@c347e8f55cbc:/opt/src# DATA_URI=https://s3.ap-south-1.amazonaws.com/gunjanpotsdam/data
root@c347e8f55cbc:/opt/src# ROOT_URI= http://s3.amazonaws.com/postdamout
root@c347e8f55cbc:/opt/src# rastervision run aws_batch -e potsdam.semantic_segmentation     -a root_uri ${ROOT_URI} -a data_uri ${DATA_URI}
Ensuring input files exist    [####################################]  100%             
Checking for existing output  [####################################]  100%
Saving command configuration to  http://s3.amazonaws.com/postdamout/chip/potsdam-seg/command-config.json...
CHIP command submitted job with jobName=CHIP_potsdamseg_0f84ab29 and jobId=53b51d90-4055-4d91-8a87-807256755cc2
Saving command configuration to  http://s3.amazonaws.com/postdamout/train/potsdam-seg/command-config.json...
TRAIN command submitted job with jobName=TRAIN_potsdamseg_cd059a9a and jobId=b425b9d6-c24d-4480-ab05-12ca27b8142c
Saving command configuration to  http://s3.amazonaws.com/postdamout/bundle/potsdam-seg/command-config.json...
BUNDLE command submitted job with jobName=BUNDLE_potsdamseg_159b94e2 and jobId=1fd03108-efe2-4d56-bd88-ff3dd6b5f4c0
Saving command configuration to  http://s3.amazonaws.com/postdamout/predict/potsdam-seg/command-config.json...
PREDICT command submitted job with jobName=PREDICT_potsdamseg_5653a42f and jobId=3f193992-a243-4cbc-88d9-eed727346a63
Saving command configuration to  http://s3.amazonaws.com/postdamout/eval/potsdam-seg/command-config.json...
EVAL command submitted job with jobName=EVAL_potsdamseg_e520e47f and jobId=ae465f02-8d7f-405d-83e2-0782545a5b8e
root@c347e8f55cbc:/opt/src#

**Comment by gunjanthakuria** [comment]
Hey Thanks,that worked  on the test run. However when I  tried running the program using AWS batch having set up the required AMIs, I again face the problem of no outputs and no error message also 
     My input and output folder are in S3:
DATA_URI=s3://gunjanpotsdam/data
ROOT_URI= s3://postdamout/output
I ran the batch command : rastervision run aws_batch -e potsdam.semantic_segmentation     -a root_uri ${ROOT_URI} -a data_uri ${DATA_URI}

However I don't see any outputs in the S3 bucket "s3://postdamout/output" nor is there any error . Am I making any mistake here ? Please find below the logs:


root@4f4e529fb316:~# ROOT_URI=s3://postdamout/output
root@4f4e529fb316:~# DATA_URI=s3://gunjanpotsdam/data
root@4f4e529fb316:~# rastervision run aws_batch -e potsdam.semantic_segmentation     -a root_uri ${ROOT_URI} -a data_uri ${DATA_URI}
Ensuring input files exist    [####################################]  100%             
Checking for existing output  [####################################]  100%             
Saving command configuration to s3://postdamout/output/chip/potsdam-seg/command-config.json...
CHIP command submitted job with jobName=CHIP_potsdamseg_fc22008b and jobId=53135eb2-2577-4b37-b65e-c00ed61343f7
Saving command configuration to s3://postdamout/output/train/potsdam-seg/command-config.json...
TRAIN command submitted job with jobName=TRAIN_potsdamseg_c6421281 and jobId=18032ec5-eadb-49e2-ad92-8f06b5473d39
Saving command configuration to s3://postdamout/output/bundle/potsdam-seg/command-config.json...
BUNDLE command submitted job with jobName=BUNDLE_potsdamseg_4686b1a7 and jobId=0bb9a468-ed03-4733-bacd-d4a5a9422d11
Saving command configuration to s3://postdamout/output/predict/potsdam-seg/command-config.json...
PREDICT command submitted job with jobName=PREDICT_potsdamseg_5cfe81f9 and jobId=d6d367ff-77fb-4463-a3bb-6195e211fbb8
Saving command configuration to s3://postdamout/output/eval/potsdam-seg/command-config.json...
EVAL command submitted job with jobName=EVAL_potsdamseg_5f468c9d and jobId=cdaeb5dc-3b0d-4602-8202-d48e05e9662a
root@4f4e529fb316:~#

**Comment by lewfish** [comment]
When you run a job on Batch, you can view the status of that job and any output in the Batch console. You will need to look at the output to see what the problem is.

**Comment by gunjanthakuria** [comment]
Thanks so much for your help and pointing me in the right direction. I  managed to run the training and validation using AWS Batch job; it turns out the instances were not launching due to volume issues which I resolved and the jobs ran successfully and the outputs are in my aws bucket.

   However I have run into another problem while using the predict_package to run predictions on other images. One of the outputs after training the model is the predict_package.zip file in the bundle folder which contains the "model" file and "bundle_config.json" file .

  However when I run the predict function from the command line ; it is not able to read the Predict_package files. I set the URI for the predict_package files, Image_uri and output_uri. I get the error "NotReadableError('Could not read {}'.format(uri))
rastervision.filesystem.filesystem.NotReadableError: Could not read Predict_Package". Can you please help me point me to the right direction to investigate what am I doing wrong here. Below is the log:


Gunjans-MacBook:~ gunjanthakuria$Predict_Package=s3://postdamout/output/undle/potsdam-seg/predict_package.zip
Gunjans-MacBook:~ gunjanthakuria$IMAGE_URI=/Users/gunjanthakuria/Desktop/output/2_13_RGBIR.tif
Gunjans-MacBook:~ gunjanthakuria$ OUTPUT_URI=/Users/Desktop/2_13.tif
Gunjans-MacBook:~ gunjanthakuria$ rastervision predict Predict_Package IMAGE_URI OUTPUT_URI
Traceback (most recent call last):
  File "/Users/gunjanthakuria/anaconda3/bin/rastervision", line 11, in <module>
    sys.exit(main())
  File "/Users/gunjanthakuria/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gunjanthakuria/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/gunjanthakuria/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gunjanthakuria/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gunjanthakuria/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/gunjanthakuria/anaconda3/lib/python3.6/site-packages/rastervision/cli/main.py", line 239, in predict
    channel_order)
  File "/Users/gunjanthakuria/anaconda3/lib/python3.6/site-packages/rastervision/predictor.py", line 40, in __init__
    package_zip_path = download_if_needed(prediction_package_uri, tmp_dir)
  File "/Users/gunjanthakuria/anaconda3/lib/python3.6/site-packages/rastervision/utils/files.py", line 136, in download_if_needed
    fs.copy_from(uri, path)
  File "/Users/gunjanthakuria/anaconda3/lib/python3.6/site-packages/rastervision/filesystem/local_filesystem.py", line 117, in copy_from
    raise NotReadableError('Could not read {}'.format(uri))
rastervision.filesystem.filesystem.NotReadableError: Could not read Predict_Package
Gunjans-MacBook:~ gunjanthakuria$

**Comment by gunjanthakuria** [comment]
Thanks so much for your help and pointing me in the right direction. I managed to run the training and validation using AWS Batch job; it turns out the instances were not launching due to volume issues which I resolved and the jobs ran successfully and the outputs are in my aws bucket.
 
  However I have run into another problem while using the predict_package to run predictions on other images. One of the outputs after training the model is the predict_package.zip file in the bundle folder which contains the "model" file and "bundle_config.json" file . When I run the predict function from the command line , I get an error saying it is **not able to parse** the JSON file. Can you please help me point me to the right direction to investigate what am I doing wrong here. Below is the log:

root@c9096928f740:~# rastervision predict https://s3.amazonaws.com/postdamout/output/bundle/potsdam-seg/predict_package.zip https://s3.ap-south-1.amazonaws.com/gunjanpotsdam/data/4_Ortho_RGBIR/top_potsdam_2_13_RGBIR.tif 2_13.tif
2019-04-04 18:12:05:rastervision.utils.files: INFO - Downloading https://s3.amazonaws.com/postdamout/output/bundle/potsdam-seg/predict_package.zip to /tmp/tmp4ms6rljf/tmpmlw_6rts/http/s3.amazonaws.com/postdamout/output/bundle/potsdam-seg/predict_package.zip
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 489, in _ConvertFieldValuePair
    message_descriptor.fields))
google.protobuf.json_format.ParseError: Message type "rv.protos.CommandConfig" has no field named "splitId".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/src/rastervision/utils/files.py", line 247, in load_json_config
    return json_format.Parse(file_to_str(uri, fs=fs), message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 406, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 421, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 452, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 554, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "rv.protos.CommandConfig" has no field named "splitId".
 Available Fields(except extensions): <MessageFields sequence>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/__main__.py", line 17, in <module>
    rv.main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/cli/main.py", line 239, in predict
    channel_order)
  File "/opt/src/rastervision/predictor.py", line 48, in __init__
    msg = load_json_config(bundle_config_path, CommandConfigMsg())
  File "/opt/src/rastervision/utils/files.py", line 251, in load_json_config
    raise ProtobufParseException(error_msg) from e
rastervision.filesystem.filesystem.ProtobufParseException: Problem parsing protobuf file /tmp/tmp4ms6rljf/tmpmlw_6rts/package/bundle_config.json. You might need to run scripts/compile

**Comment by lewfish** [comment]
The `splitId` was recently added to RV. So it looks like you generated a predict package with a recent version of RV that wrote a `splitId` value, and are running the `predict` command using an older version of RV that doesn't recognize that field.

**Comment by lewfish** [comment]
I just confirmed that the `predict` command you ran works with the `master` branch of RV (or `-latest` Docker image).

**Comment by gunjanthakuria** [comment]
Thanks; I believe now I am running the latest version of RV for both training and prediction from the latest docker image. However I am still facing problems with predict_package.The error that now I am getting is that DeeplabConfig is not able to find  field names doEval. Can you please help me out here

google.protobuf.json_format.ParseError: Message type "rv.protos.BackendConfig.TFDeeplabConfig" **has no field named "doEval".** 

Below is the complete log 
root@e2601c724dc9:/opt/src# rastervision predict https://s3.amazonaws.com/postdamout/output/bundle/potsdam-seg/predict_package.zip https://s3.ap-south-1.amazonaws.com/gunjanpotsdam/data/4_Ortho_RGBIR/top_potsdam_2_13_RGBIR.tif /opt/data/2_13.tif
2019-04-05 07:37:20:rastervision.utils.files: INFO - Downloading https://s3.amazonaws.com/postdamout/output/bundle/potsdam-seg/predict_package.zip to /tmp/tmpsh8e20v3/tmp39mr3ake/http/s3.amazonaws.com/postdamout/output/bundle/potsdam-seg/predict_package.zip
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 489, in _ConvertFieldValuePair
    message_descriptor.fields))
google.protobuf.json_format.ParseError: Message type "rv.protos.BackendConfig.TFDeeplabConfig" has no field named "doEval".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 547, in _ConvertFieldValuePair
    self.ConvertMessage(value, sub_message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 452, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 554, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "rv.protos.BackendConfig.TFDeeplabConfig" has no field named "doEval".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 547, in _ConvertFieldValuePair
    self.ConvertMessage(value, sub_message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 452, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 554, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "rv.protos.BackendConfig.TFDeeplabConfig" has no field named "doEval".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 547, in _ConvertFieldValuePair
    self.ConvertMessage(value, sub_message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 452, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 552, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse backend field: Message type "rv.protos.BackendConfig.TFDeeplabConfig" has no field named "doEval".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/src/rastervision/utils/files.py", line 247, in load_json_config
    return json_format.Parse(file_to_str(uri, fs=fs), message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 406, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 421, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 452, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 554, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Failed to parse backend field: Message type "rv.protos.BackendConfig.TFDeeplabConfig" has no field named "doEval".
 Available Fields(except extensions): <MessageFields sequence>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/__main__.py", line 17, in <module>
    rv.main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/cli/main.py", line 239, in predict
    channel_order)
  File "/opt/src/rastervision/predictor.py", line 48, in __init__
    msg = load_json_config(bundle_config_path, CommandConfigMsg())
  File "/opt/src/rastervision/utils/files.py", line 251, in load_json_config
    raise ProtobufParseException(error_msg) from e
rastervision.filesystem.filesystem.ProtobufParseException: Problem parsing protobuf file /tmp/tmpsh8e20v3/tmp39mr3ake/package/bundle_config.json. You might need to run scripts/compile
root@e2601c724dc9:/opt/src#

**Comment by lewfish** [comment]
I still think this is a versioning issue. I would verify that the Docker image is indeed the latest published one. There might be some special command you need to run to force it to pull the latest instead of using the cached one.

**Comment by gunjanthakuria** [comment]
I managed to run the predict function by building the Docker image again and running the container  using  docker/build and docker/run .

   However when I install rastervision on my CPU machine using "pip install rastervision" it is still not able to parse the JSON file. The rastervision version that gets installed is 0.8.1

**Comment by lewfish** [comment]
I'm assuming you are pip installing in order to use the QGIS plugin. The published version will not work with the master branch of RV. Using the published QGIS plugin at the moment will require using 0.8.1 of RV. BTW, we are having a new release in the next week.
